services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb://dcgpu_lab:amd12345@mongodb:27017/lab-monitoring
      - MONGO_PORT=27017
      - MONGO_DB=lab-monitoring
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3005:3005"
    depends_on:
      - backend

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dcgpu_lab
      MONGO_INITDB_ROOT_PASSWORD: amd12345
      MONGO_INITDB_DATABASE: lab-monitoring
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
