services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3005:3005"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: